version: '3.7'

services:
  django: 
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=myuser
      - DB_PASSWORD=123
      - DB_NAME=mydb
      - DB_HOST=postgres
      - PYTHONPATH=/test/backendTests
    volumes:
      - "./django:/django"
      - "../../test:/test"
    command: python3 manage.py runserver 0.0.0.0:8000
    image: app:django
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"